# Generated by Django 4.1.1 on 2022-10-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=200)),
                ('your_email', models.CharField(max_length=200)),
                ('player_s_choices', models.TextField(max_length=1000)),
            ],
        ),
    ]
